# Generated by Django 2.1.1 on 2018-09-08 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5, 'Maximun rating is 5'), django.core.validators.MinValueValidator(1, 'Minimun rating is 1')]),
        ),
    ]
